asp_mvc_blog_hieunt/Controllers/BlogsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using asp_mvc_blog_hieunt.Models;

namespace asp_mvc_blog_hieunt.Controllers
{
    public class BlogsController : Controller
    {
        private BlogDBContext db = new BlogDBContext();
        List<string> listpos = new List<string> { "Việt Nam", "Châu Á", "Châu Âu", "Châu Mỹ" };

        // GET: Blogs
        public ActionResult Index()
        {
            return View(db.Blogs.ToList());
        }

        // GET: Blogs/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Blog blog = db.Blogs.Find(id);
            if (blog == null)
            {
                return HttpNotFound();
            }
            return View(blog);
        }

        // GET: Blogs/Create
        public ActionResult Create()
        {
            var list = new SelectList(db.Categories.ToList(), "ID", "Title");
            ViewData["listCategories"] = list;
            return View();
        }

        // POST: Blogs/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,title,shortDetail,detail,thumb,status,datePublic,CategoryId")] Blog blog)
        {

            if (ModelState.IsValid)
            {

                db.Blogs.Add(blog);
                db.SaveChanges();
                for (int i = 1; i <= 4; i++)
                {
                    string checkbox = "checkbox" + i;
                    if (Request.Form[checkbox] != null)
                    {
                        Position position = new Position();
                        position.BlogId = blog.ID;
                        position.address = Request.Form[checkbox];
                        position.ID = 0;
                        db.Positions.Add(position);
                    }
                }
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(blog);
        }

        // GET: Blogs/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Blog blog = db.Blogs.Find(id);
            var list = new SelectList(db.Categories.ToList(), "ID", "Title");
            ViewData["listCategories"] = list;
            for (int i = 0; i < 4; i++)
            {
                string checkbox = "checkbox" + (i + 1);
                if (blog.Positions.Where(m => m.address == listpos[i]).Count() > 0)
                    ViewData[checkbox] = "checked";
                else
                {
                    ViewData[checkbox] = "";
                }
            }

            if (blog == null)
            {
                return HttpNotFound();
            }
            return View(blog);
        }

        // POST: Blogs/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,title,shortDetail,detail,thumb,status,datePublic,CategoryId")] Blog blog)
        {
            if (ModelState.IsValid)
            {
                db.Entry(blog).State = EntityState.Modified;
                db.SaveChanges();
                db.Positions.RemoveRange(db.Positions.ToList().FindAll(m => m.BlogId == blog.ID).ToList());
                for (int i = 1; i <= 4; i++)
                {
                    string checkbox = "checkbox" + i;
                    if (Request.Form[checkbox] != null)
                    {
                        Position position = new Position();
                        position.BlogId = blog.ID;
                        position.address = Request.Form[checkbox];
                        position.ID = 0;
                        db.Positions.Add(position);
                    }
                }
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(blog);
        }

        // GET: Blogs/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Blog blog = db.Blogs.Find(id);
            db.Blogs.Remove(blog);
            db.Positions.RemoveRange(db.Positions.ToList().FindAll(m => m.BlogId == blog.ID).ToList());
            if (blog == null)
            {
                return HttpNotFound();
            }
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        // POST: Blogs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Blog blog = db.Blogs.Find(id);
            db.Blogs.Remove(blog);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult Searching(FormCollection fc, string title)
        {
            var searchedBlogs = from m in db.Blogs select m;
            if (!String.IsNullOrEmpty(title))
            {
                searchedBlogs = searchedBlogs.Where(s => s.title.Contains(title));
            }
            return View(searchedBlogs);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

asp_mvc_blog_hieunt/Views/Shared/_Footer.cshtml
<footer>
    <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
</footer>

asp_mvc_blog_hieunt/Views/Shared/_Header.cshtml
<div class="d-flex blog-header navbar-fixed-top">
    <div class='col-md-3 col-lg-2 header-img '>
        <a class='' href="/Home">
            <img src='https://devfast.us/images/devfast-logo.png' class='headerlink'>
            </img>
        </a>
    </div>
    <div class='col text-center'>
        <h1 style="color:white">Blogmanagement</h1>
    </div>
</div>

asp_mvc_blog_hieunt/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    @Html.Partial("_Header")
    <div class="d-flex">
        @Html.Partial("_Menu")
        <div class="container body-content ">
            @RenderBody()
            <hr />
            <footer>
                @Html.Partial("_Footer")
                @*<p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>*@
            </footer>
        </div>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

asp_mvc_blog_hieunt/Views/Shared/_Menu.cshtml
<div class='col-2 menu-position '>
    <div class=''>
        <ul class='p-0 flex-column'>
            <li class="box-list">
                @Html.ActionLink("List", "Index", "Blogs")
            </li>
            <li class="box-list">
                @Html.ActionLink("Create", "Create", "Blogs")
            </li>
            <li class="box-list">
                @Html.ActionLink("Search", "Searching", "Blogs")
            </li>
        </ul>
    </div>
</div>